// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"app-futbol/src/config"
	"app-futbol/src/controllers"
	"app-futbol/src/database"
	"app-futbol/src/services"
	"gorm.io/gorm"
	"log"
)

// Injectors from wire.go:

func initializeApp() (*AppContainer, error) {
	configConfig := config.NewConfig()
	db := database.NewDatabase(configConfig)
	rolService := services.NewRolService(db)
	rolController := controllers.NewRolController(rolService)
	appContainer := &AppContainer{
		Config:        configConfig,
		DB:            db,
		RolService:    rolService,
		RolController: rolController,
	}
	return appContainer, nil
}

// wire.go:

type AppContainer struct {
	Config        *config.Config
	DB            *gorm.DB
	RolService    *services.RolService
	RolController *controllers.RolController
}

// Función pública: la usas en main.go
func InitializeApp() *AppContainer {
	container, err := initializeApp()
	if err != nil {
		log.Fatalf("❌ Error inicializando dependencias: %v", err)
	}
	return container
}
