root = "."
tmp_dir = "tmp"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
delay = 1000

[build]
# cmd /C permite ejecutar múltiples comandos en Windows
cmd = "cmd /C \"swag init -g main.go && go run main.go\""
bin = "./tmp/main.exe"
