// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"app-futbol/config"
	"app-futbol/database"
	"gorm.io/gorm"
)

// Injectors from yo.go:

// Injector que crea la BD lista usando Config
func InitializeDatabase() *gorm.DB {
	configConfig := config.NewConfig()
	db := database.NewDatabase(configConfig)
	return db
}
